fieldnames = ["vendorName",
              "fileFormatVersion",
                "input_file_name",
                "elementType",
                "beginTime",
                "endTime",
                "duration" ,
                "userLabel",
                  "measInfoId",
                    "duration",
                      "endTime",
                        "measTypes",
                          "measResults_row_values"]